### ISSUE TITLE
balena release fail 

### ISSUE THREAD

**Issue by Roundhead22** [jaomaloy/balena-rtl-power#1]
i pressed deploy with balena then selected my device [raspberry pi 3 using wifi] added my wifi ssid and psk it created the fleet but then failed to create here are the logs i see 
![image](https://user-images.githubusercontent.com/92760172/150199717-ccccb8dc-5d2a-40b4-9c9b-3bbf172ef239.png)

here is the docker cmpose yml docker-compose.yml

version: '2.1'
volumes:
  influxdb-data: {}
  dashboard-data: {}
services:
  grtlp:
    build:
      context: ./grtlp
    restart: always
    privileged: true
    network_mode: host
  mqtt:
    image: 'eclipse-mosquitto:1.6.15'
    restart: always
    privileged: false
    ports:
      - '1883:1883'
  connector:
    image: 'balenablocks/connector:latest'
    restart: always
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: '1'
    privileged: true
    ports:
      - '8080'
  influxdb:
    image: >-
      arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
    restart: always
    privileged: false
    volumes:
      - 'influxdb-data:/var/lib/influxdb'
  dashboard:
    build:
      context: ./dashboard
    restart: always
    privileged: false
    volumes:
      - 'dashboard-data:/data'
    ports:
      - '80'

an the build logs 

[Info]       Starting build for ***********, user **********
[Info]       Dashboard link: https://dashboard.balena-cloud.com/apps/1901536/devices
[Error]      Could not detect project type: Service dashboard: Could not find a Dockerfile for this service
[Error]      Not deploying release.

**Comment by jaomaloy** [comment]
Hi @Roundhead22 , can you try directly putting the path of the dashboard folder using the `build` option for the service? i. e

```
dashboard:
  build: ./dashboard
  restart: always
  privileged: false
  volumes:
    - 'dashboard-data:/data'
  ports:
    - '80'
```

or you could try to reference the Dockerfile.template path using the `dockerfile` option under `context` as so

```
dashboard:
  build:
    context: ./dashboard
    dockerfile: ./dashboard/Dockerfile.template
  restart: always
  privileged: false
  volumes:
    - 'dashboard-data:/data'
  ports:
    - '80'
```
